"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/backoffice/Sidebar";
import Navbar from "@/components/backoffice/Navbar";
import {useState} from "react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Ample Plus Ecommerce Shop",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const [showSidebar, setShowSidebar] = useState(false)
  return (
 <div className='flex '>
   {/*sidebar*/}
<Sidebar showSidebar={showSidebar}  setShowSidebar={setShowSidebar} />

     <div className='flex-grow bg-light text-light dark:bg-dark dark:text-dark  min-h-screen'>
     <Navbar setShowSidebar={setShowSidebar} showSidebar={showSidebar}/>

         <main className="p-8 bg-light text-light dark:bg-dark dark:text-dark  min-h-screen mt-16  ">
             {children}
         </main>
     </div>
 </div>
  );
}
