"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/backoffice/Sidebar";
import Navbar from "@/components/backoffice/Navbar";
import {useState, useEffect} from "react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Ample Plus Ecommerce Shop",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const [showSidebar, setShowSidebar] = useState(false)
    const [isMounted, setIsMounted] = useState(false);

    useEffect(() => {
        setIsMounted(true);
    }, []);

    if (!isMounted) {
        return null;
    }
  return (
 <div className='flex '>
   {/*sidebar*/}
<Sidebar showSidebar={showSidebar}  setShowSidebar={setShowSidebar} />
     {/*lg:ml-60 ml-0*/}

     {/* ml-60*/}
     <div className=' flex-grow  min-h-screen bg-light text-light dark:bg-dark dark:text-dark'>
     <Navbar setShowSidebar={setShowSidebar} showSidebar={showSidebar}/>

         <main className="p-8 bg-slate-50 text-light dark:bg-slate-800 dark:text-dark min-h-screen mt-16  ml-60">
             {children}
         </main>
     </div>
 </div>
  );
}
