import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/backoffice/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ample Plus Ecommerce Shop",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 <div className='flex'>
   {/*sidebar*/}
<Sidebar/>

     <div className='w-full'>
         <h2>
             nAVBAR
         </h2>

         <main>
             {children}
         </main>
     </div>
 </div>
  );
}
